version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          make build || exit 1
  release:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          make release TAG=$CIRCLE_TAG || exit 1
workflows:
  version: 2
  test_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
