version: 2

defaults: &defaults
  working_directory: /tmp/grpcgen

jobs:
  build:
    <<: *defaults
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          mkdir build && echo 123 >> /tmp/grpcgen/build/rootfs.tar.gz
      - persist_to_workspace:
          root: build
          paths:
            - rootfs.tar.gz
  release:
    <<: *defaults
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/grpcgen
      - run: |
          ls -l
workflows:
  version: 2
  test_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
